### PR TITLE
Related to issue #5, regarding the absence of code using DatasetFromCSV

### PR DESCRIPTION
**Pull request by genevievebo**
Added two notebooks to show an example of how to use a custom dataset, regarding comment made for #3

### CODE REVIEW

**Comment by ieee8023** [comment]
So it seems that the auto-downloading feature is making the code hard to work with? Should it be factored so that you download the file external to the function? You can construct it like this as well to put the datastore where you want:
```
import academictorrents as at
filepath = at.get("2b7e470d87a017be3826ef6ec55893f3a61f5af7", datastore="..")
GeneManiaGraph(filepath)
```

Also, I see in the notebook you loaded AML data to recreate the experiments on S100A8. Did you try the genemania graph on some clinical targets as well?

**Comment by genevievebo** [comment]
No, I didn't try on clinical targets yet.  The data I've used is from TARGET (Therapeutically Applicable Research To Generate Effective Treatments), which focuses on childhood cancers (AML and other types).  I've used the pan-cancer matrix available from the UCSC Xena Browser.

**Comment by genevievebo** [comment]
For the graph loading, I'm not sure I would use academic torrents directly in the notebook.  The issue I had was that I moved the notebook in another directory which led to a re-download of the file.  Having a way to specify the path to the datastore when loading (or downloading) a gene interaction graph might be helpful.

**Comment by ieee8023** [comment]
You should be able to specify an absolute path for the datastore. datastore="~/datastore"

**Comment by mweiss17** [comment]
@genevievebo @ieee8023 I fixed this issue in the latest academictorrents. If you pull master on `gene-graph-conv` then run `pip install -r requirements.txt` you will get academictorrents version 2.1.3 which should do a better job handling datastore paths. The relevant function is here: https://github.com/AcademicTorrents/at-python/blob/master/academictorrents/utils.py#L28

**Pull request merged**
